name: release-please-dev

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-dev:
    runs-on: ubuntu-latest
    # Only run if CI passed successfully and commit is not from release-please itself
    if: |
      (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') &&
      !startsWith(github.event.workflow_run.head_commit.message, 'chore(dev): release')
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config-dev.json
          manifest-file: .release-please-manifest-dev.json
          target-branch: dev
